version: '2.2'

services:
  chimera-example: 
    image: cefriel/chimera:tutorial-advanced
    build: 
        context: ./
    mem_limit: 4g
    ports:
      - 8888:8888
    networks:
      - chimera-net

networks:
  chimera-net:
    driver: bridge